import os
from dotenv import load_dotenv

from config.log.logger import setup_logger


logger = setup_logger(__name__)

# Load environment variables from .env file
logger.debug("Loading app settings")
try:
    load_dotenv()

    # ----- Todoist API Token (defined on .env) ----------------------------
    TODOIST_API_TOKEN = os.getenv("TODOIST_API_TOKEN")
    if not TODOIST_API_TOKEN:
        logger.error(
            "Missing TODOIST_API_TOKEN in .env. Please create a .env file with your Todoist API token (`TODOIST_API_TOKEN=<yourtokenhere>`)."
        )

    # ----- Google calendar credentials (defined on .env) ------------------
    GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH")
    GOOGLE_TOKEN_PATH = os.getenv("GOOGLE_TOKEN_PATH")

    if not GOOGLE_CREDENTIALS_PATH:
        logger.error(
            "Missing GOOGLE_CREDENTIALS_PATH in .env file `google_credentials.json` not found."
        )

    if not GOOGLE_TOKEN_PATH:
        logger.error(
            "Missing GOOGLE_CREDENTIALS_PATH in .env file `google_token.json` not found (File should be autogenerated)."
        )

except Exception as e:
    logger.error(f"Error loading app settings: {e}")
    print(f"Error loading app settings: {e}")

# ----- Default table format for CLI output using tabulate -------------
DEF_TABLE_FMT = "rounded_outline"

# ----- Default date/time format ---------------------------------------
DEF_DATETIME_FMT = "%Y-%m-%d %H:%M"
