import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ----------------------------------------------------------------------
# Todoist API Token (defined on .env)
# ----------------------------------------------------------------------
TODOIST_API_TOKEN = os.getenv("TODOIST_API_TOKEN")
if not TODOIST_API_TOKEN:
    raise ValueError(
        "[ERROR] Missing TODOIST_API_TOKEN in .env. Please create a .env file with your Todoist API token (`TODOIST_API_TOKEN=<yourtokenhere>`)."
    )

# ----------------------------------------------------------------------
# Google calendar credentials (defined on .env)
# ----------------------------------------------------------------------
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH")
GOOGLE_TOKEN_PATH = os.getenv("GOOGLE_TOKEN_PATH")

if not GOOGLE_CREDENTIALS_PATH:
    raise ValueError(
        "[ERROR] Missing GOOGLE_CREDENTIALS_PATH in .env file `google_credentials.json` not found."
    )

if not GOOGLE_TOKEN_PATH:
    raise ValueError(
        "[ERROR] Missing GOOGLE_CREDENTIALS_PATH in .env file `google_token.json` not found (File should be autogenerated)."
    )

# ----------------------------------------------------------------------
# Default table format for CLI output using tabulate
# ----------------------------------------------------------------------
DEFAULT_TABLEFORMAT = "rounded_outline"
