import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ----------------------------------------------------------------------
# Todoist API Token
# ----------------------------------------------------------------------
TODOIST_API_TOKEN = os.getenv("TODOIST_API_TOKEN")
if not TODOIST_API_TOKEN:
    raise ValueError(
        "Missing TODOIST_API_TOKEN in .env. "
        "Please create a .env file with your token."
    )

# ----------------------------------------------------------------------
# Google calendar credentials
# ----------------------------------------------------------------------
GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH")
GOOGLE_TOKEN_PATH = os.getenv("GOOGLE_TOKEN_PATH")

if not GOOGLE_CREDENTIALS_PATH:
    raise ValueError(
        "Missing GOOGLE_CREDENTIALS_PATH in .env"
        "Please create a .env file with your google_credentials.json file path."
    )

if not GOOGLE_TOKEN_PATH:
    raise ValueError(
        "Missing GOOGLE_CREDENTIALS_PATH in .env"
        "Please create a .env file with your google_token.json desired path (file will be autogenerated)"
    )

# ----------------------------------------------------------------------
# Google calendar IDs
# ----------------------------------------------------------------------
GCAL_ID_MYTASKS=os.getenv("GCAL_ID_MYTASKS")
GCAL_ID_WORK=os.getenv("GCAL_ID_WORK")
GCAL_ID_TIMEMANAGE=os.getenv("GCAL_ID_TIMEMANAGE")
GCAL_ID_PERSONALEVENTS=os.getenv("GCAL_ID_PERSONALEVENTS")

# ----------------------------------------------------------------------
# Default label for non-scheduled tasks
# ----------------------------------------------------------------------
NONSCHEDULED_TASKS_LABEL = "Agendar"

# ----------------------------------------------------------------------
# Default table format for CLI output using tabulate
# ----------------------------------------------------------------------
DEFAULT_TABLEFORMAT = "rounded_outline"

