# BUG: GCalClient tests failing in CI
# GCalClient-related tests fail only in GitHub Actions
# due to credential path initialization and the implicit
# dependency on authentication. They pass locally.
# assignees: userS4B0
# labels: priority_medium, bug, cicd
# milestone: v1.0.0

name: Run Tests

# Triggers
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      # Obtain codebase
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Execute tests
      - name: Run tests with coverage
        run: |
          pytest --cov=src --maxfail=1 --disable-warnings
